<!DOCTYPE debitCredit [
  <!ELEMENT debitCredit (cardInfo*)>
  <!ELEMENT cardInfo (holderName, cardNumber,billingAddress, expiryDate, CVV)>
  
  <!ELEMENT holderName (#PCDATA)>
  <!ELEMENT cardNumber (#PCDATA)>
  <!ELEMENT expiryDate (#PCDATA)>
  <!ELEMENT billingAddress (#PCDATA)>
  <!ELEMENT CVV (#PCDATA)>
]>

<debitCredit>
  <cardInfo>
    <holderName>John Smith</holderName>
    <cardNumber>5748384739582957</cardNumber>
    <billingAddress>11 Lime Street, Grand Canal Dock</billingAddress>
    <expiryDate>06/25</expiryDate>
    <CVV>321</CVV>
  </cardInfo>
  
  <cardInfo>
    <holderName>Mary Murphy</holderName>
    <cardNumber>9013284528563965</cardNumber>
    <billingAddress>81 Ormond Road, Drumcondra</billingAddress>
    <expiryDate>01/27</expiryDate>
    <CVV>597</CVV>
  </cardInfo>
</debitCredit>
